import "dotenv/config";
import { Pool } from "pg";
import fs from "fs";
import path from "path";
import { runDetectors, Bar } from "./detectors/index.js";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is required");
}

const pool = new Pool({ connectionString: databaseUrl });

/**
 * Signal Engine Main Loop
 * Reads "daily_opportunities.json" from the shared volume (or automation output)
 * and simulates scanning those specific assets.
 */
async function main() {
  console.log("🚀 Signal Engine started. Monitoring for closed bars...");

  // Path to the opportunities file generated by automation service
  const FALLBACK_TICKERS = ["NVDA", "AMD", "TSLA", "BTC-USD", "ETH-USD", "COIN", "MSTR"];

  const getWatchlist = () => {
    try {
      // Try to find the files in the shared volume
      const contentDir = "/app/content";
      const day = JSON.parse(fs.readFileSync(path.join(contentDir, "day_candidates.json"), "utf-8"));
      const swing = JSON.parse(fs.readFileSync(path.join(contentDir, "swing_candidates.json"), "utf-8"));
      const invest = JSON.parse(fs.readFileSync(path.join(contentDir, "invest_candidates.json"), "utf-8"));
      
      const combined = [...new Set([...day, ...swing, ...invest])];
      if (combined.length > 0) return combined;
      
      return FALLBACK_TICKERS;
    } catch {
      return FALLBACK_TICKERS;
    }
  };

  const mockStream = async function* () {
    const watchlist = getWatchlist();
    let index = 0;

    while (true) {
      await new Promise(r => setTimeout(r, 5000)); // Every 5s emit a bar
      
      const symbol = watchlist[index % watchlist.length];
      index++;

      // Generate realistic-looking bar
      const basePrice = Math.random() * 100 + 100;
      const volatility = basePrice * 0.02;
      const open = basePrice;
      const close = basePrice + (Math.random() - 0.5) * volatility;
      const high = Math.max(open, close) + Math.random() * volatility * 0.5;
      const low = Math.min(open, close) - Math.random() * volatility * 0.5;
      
      // Inject "Setup" conditions occasionally
      const isSetup = Math.random() > 0.8; 
      const delta = isSetup ? (Math.random() > 0.5 ? -50000 : 50000) : (Math.random() - 0.5) * 1000;

      const bar: Bar = {
        symbol,
        venue: symbol.includes("-") ? "CRYPTO" : "NASDAQ",
        assetType: symbol.includes("-") ? "CRYPTO" : "STOCK",
        open, high, low, close,
        volume: Math.floor(Math.random() * 1000000) + 500000,
        time: new Date().toISOString(),
        interval: "15m",
        delta: delta,
        cvd: delta * 5,
        hvn_levels: [low - 1, high + 1] // Mock HVNs
      };

      yield bar;
    }
  };

  for await (const bar of mockStream()) {
    const signals = runDetectors(bar);
    
    for (const signal of signals) {
      try {
        const res = await pool.query(
          `insert into signals (
            symbol, venue, asset_type, pattern, features, entry, sl, tp1, tp2, tp3,
            confidence, bar_time, seen_time, interval, data_latency_ms, vendor, class_scope, options_meta
          ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
          returning id`,
          [
            signal.symbol, signal.venue, signal.assetType, signal.pattern,
            signal.features, signal.entry, signal.sl, signal.tp1, signal.tp2, signal.tp3,
            signal.confidence, signal.barTime, signal.seenTime, signal.interval,
            signal.dataLatencyMs, signal.vendor, signal.classScope, signal.optionsMeta
          ]
        );

        const signalId = res.rows[0].id;
        console.log(`✅ Signal Generated: ${signal.pattern} for ${signal.symbol} (${signalId})`);

        // Promote to Live Feed
        await pool.query(
          `insert into signals_live (signal_id, status, first_seen, last_seen, dedupe_hash)
           values ($1, 'active', now(), now(), $2)
           on conflict (dedupe_hash) do nothing`,
          [signalId, `${signal.symbol}-${signal.pattern}-${signal.barTime}`]
        );

        // Schedule Public Feed (15m delay)
        await pool.query(
          `insert into public_feed (signal_id, published_at, delay_minutes)
           values ($1, now() + interval '15 minutes', 15)`,
          [signalId]
        );

      } catch (err) {
        console.error("❌ Failed to save signal:", err);
      }
    }
  }
}

main().catch(console.error);